version: '3.9'

services:
  # NEXT.JS APP
  nextjs-app:
    build:
      context: ./app/observe-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app/observe-app:/app
    working_dir: /app
    environment:
      - NODE_ENV=production
    env_file:
      - ./app/observe-app/.env.local
    depends_on:
      - ollama
      - mssql
      - mysql
      - postgres
    networks:
      - app-net

  # OLLAMA (SQLCoder, LLM)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - app-net
    restart: unless-stopped

  # MSSQL SERVER
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - app-net
    restart: unless-stopped

  # MySQL
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-net
    restart: unless-stopped

  # PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - app-net
    restart: unless-stopped

volumes:
  ollama-data:
  mssql-data:
  mysql-data:
  pg-data:

networks:
  app-net:
    driver: bridge
